# Generated by Django 3.2.8 on 2023-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_note_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='note_img',
            field=models.ImageField(blank=True, null=True, upload_to='note_images'),
        ),
    ]
